ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcUrl: "jdbc:postgresql://localhost:5432/spotify_db"
  username: "postgres"
  password: "montes123"

jwt:
  secret: "mi_secreto_super_seguro_123"
  domain: "https://spotify-api.com"
  audience: "spotify-users"
  realm: "Spotify Access"

aws:
  accessKey: "TU_ACCESS_KEY_DE_AWS"
  secretKey: "TU_SECRET_KEY_DE_AWS"
  region: "us-east-1"
  bucketName: "tu-bucket-spotify"