ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcUrl: "jdbc:postgresql://localhost:5432/spotify_db"
  username: "postgres"
  password: "montes123"

jwt:
  secret: "mi_secreto_super_seguro_123"
  domain: "https://spotify-api.com"
  audience: "spotify-users"
  realm: "Spotify Access"

aws:
  bucketName: "amzn-bucket-spotify-api01"
  region: "us-east-1"
  accessKey: "ASIAVJFGFXDEHHXELG3U"
  secretKey: "LdgMU/+vaWcRbWTjOXoMXoAnnlMl5sWwi2ObVuei"
  sessionToken: "IQoJb3JpZ2luX2VjEP///////////wEaCXVzLXdlc3QtMiJIMEYCIQCKb7MzaME71k2eIVM6n6vSc4ossE8zlnFnAL/czxkVdAIhAIrbAG735j/RKynAA4gIh2HdPGwIcIEhQ6a3nASGiE/yKr4CCMj//////////wEQARoMMzYzMjczMjM4NzI4IgyfFqEaqgJflFbZU00qkgJlMqTQ5yQme0dUc02VBqHk+0U1a8HsWRJilHVEBtG2VBiePOn43xLX3w0iA2HZ7xLaHWptN9ABes57rjVuIYNwN5NADOKknagaCMNnPCcgVIFsQVnoVo1Xm9tDWafqx1BLvPXf34CJywZgyT3NIFAP6ieHg4SyyqqXJJxDqzMimcdHW0EtYtmVwp9lLLMjRdBUyG1BtXCmVXcIuQxtc399FfhvzYSdM1McSYRYu8YKhkiQvgbSDiKFZfF4HoUWiFsnrb8p+dazKIhXOhbP9nMLOATMD0+1CyvvoK2b33elWGhndkk2SUxwz3AfUy+iUFD1v8Cu/OjqzPQpeUiLTvTAZ21644dmcRqM1GNpL9cJbR6/MO2zqskGOpwBRAzm6ZTgWc+OQcDL6zMz5ItaF1rwM0jPkEao0zzM18THepsL9rUSKWFldWSoaYllDiIkHWzHPpebG37cpm4RYqLBos1mPGyv+SSYv3qsbpsXxMR+8p3NlWvEaVnGGI/YM4h7PjndQa8BNhygxpIN2nS7IYmZ1rsn1WDDZ1PNwlDopUvJEK1n+WTiLJZ3v7VP93uLDo87eH5kFscx"